name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '***NO_CI***')"
    steps:
      - name: Establish Git User
        run: |
          git config --global user.email "53619745+rnbot@users.noreply.github.com"
          git config --global user.name "React-Native Bot"
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
          persist-credentials: true
      - name: Install Node 15
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x
      - name: Cache /.yarn-offline-mirror
        uses: actions/cache@v2
        with:
          path: .yarn-offline-mirror
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install package dependencies
        run: yarn ci
      - name: Build and test packages
        run: yarn build:ci
      - name: Bundle packages
        run: yarn bundle:ci
      - name: Publish
        run: yarn run publish:beachball --yes --token ${{ secrets.NPM_TOKEN }}
