name: Build and Publish
on:
  push:
    branches: [main]
env:
  NODE_OPTIONS: "--disable-proto=delete"
jobs:
  build_and_publish:
    name: "Build and publish"
    permissions:
      contents: write # for GH releases and Git tags (Changesets)
    if: ${{ github.repository == 'microsoft/rnx-kit' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Setup the toolchain
        uses: microsoft/react-native-test-app/.github/actions/setup-toolchain@4.4.5
      - name: Install package dependencies
        run: |
          yarn
      - name: Build and test packages
        run: |
          yarn build:ci:all
      - name: Bundle packages
        run: |
          yarn bundle
      - name: Generate token for publishing
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write # for GH releases and Git tags (Changesets)
          permission-pull-requests: write # version PRs (Changesets)
      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn publish:changesets
          version: yarn version:changesets
        env:
          # We cannot use the GHA generated tokens because we've disabled
          # creation of pull requests at the org level.
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  website:
    name: "Publish website"
    permissions:
      contents: write # deploy to GitHub Pages (peaceiris/actions-gh-pages)
    needs: build_and_publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - name: Install package dependencies
        run: |
          yarn
        working-directory: docsite
      - name: Build website
        run: |
          yarn build
        working-directory: docsite
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsite/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
